AWSTemplateFormatVersion: "2010-09-09"
Resources: 
  jpSourceQueue: 
    Type: AWS::SQS::Queue
    Properties:
      DelaySeconds: 0
      MaximumMessageSize: 262144
      MessageRetentionPeriod: 3600
      QueueName: jplabqueue01.fifo
      FifoQueue: true
      ContentBasedDeduplication: true
      ReceiveMessageWaitTimeSeconds: 0 
      VisibilityTimeout: 10
      RedrivePolicy: 
        deadLetterTargetArn: 
          Fn::GetAtt: 
            - "jpDeadLetterQueue"
            - "Arn"
        maxReceiveCount: 2
  jpDeadLetterQueue: 
    Type: AWS::SQS::Queue
    Properties:
      DelaySeconds: 0
      MaximumMessageSize: 262144
      MessageRetentionPeriod: 36000
      QueueName: jpdlq01.fifo
      FifoQueue: true
      ContentBasedDeduplication: true
      ReceiveMessageWaitTimeSeconds: 0 
      VisibilityTimeout: 10
Outputs: 
  SourceQueueURL: 
    Description: "URL of source queue"
    Value: 
      Ref: "jpSourceQueue"
  SourceQueueARN: 
    Description: "ARN of source queue"
    Value: 
      Fn::GetAtt: 
        - "jpSourceQueue"
        - "Arn"
  DeadLetterQueueURL: 
    Description: "URL of dead-letter queue"
    Value: 
      Ref: "jpDeadLetterQueue"
  DeadLetterQueueARN: 
    Description: "ARN of dead-letter queue"
    Value: 
      Fn::GetAtt: 
        - "jpDeadLetterQueue"
        - "Arn"
